routes/web.php
<?php

use App\Http\Controllers\Front\BookingController;
use App\Http\Controllers\Front\BranchController;
use App\Http\Controllers\Front\HallController;
use App\Http\Controllers\Front\LandingPageController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('index');
// });

Route::get('/',[LandingPageController::class,'index'])->name('landingpage');

// branch
Route::resource('branches',BranchController::class);
// hall
Route::resource('halls',HallController::class);
// booking
Route::resource('bookings',BookingController::class);

Route::post('/bookings/fetchhalls',[BookingController::class,'fetchHalls'])->name('bookings.fetchhalls');
Route::post('/bookings/isavailable',[BookingController::class,'isAvailable'])->name('bookings.isavailable');

app/Models/Booking.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Booking extends Model
{
    use HasFactory;

    protected $table="bookings";
    protected $fillable=['booked_by','branch_id','hall_id','date','start_time','end_time','reason'];


    public function branch()
    {
        return $this->belongsTo('App\Models\Branch');
    }

    public function hall()
    {
        return $this->belongsTo('App\Models\Hall');
    }
}

app/Http/Controllers/Front/BookingController.php
<?php

namespace App\Http\Controllers\Front;

use App\Http\Controllers\Controller;
use App\Models\Booking;
use App\Models\Branch;
use App\Models\Hall;
use Exception;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class BookingController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $bookings = Booking::get();
        return view('bookings.index', [
            'bookings' => $bookings,
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $branches = Branch::get();
        $halls = Hall::get();
        return view('bookings.create', [
            'branches' => $branches,
            'halls' => $halls,
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        try {
            DB::beginTransaction();
            $data = $this->validate($request, [
                'booked_by' => 'required|string|max:191',
                'reason' => 'required|string|max:191',
                'date' => 'required|date',
                'start_time' => 'required|date_format:H:i',
                'end_time' => 'required|date_format:H:i',
                'branch_id' => 'required|numeric',
                'hall_id' => 'required|numeric',
            ]);
            Booking::create($data);
            DB::commit();
            session()->flash('success', 'booking has been created successfully');
            return redirect()->back();
        } catch (Exception $exception) {
            DB::rollBack();
            return redirect()->back()->with('danger', $exception->getMessage())->withInput();
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        try {
            $booking = Booking::findOrFail($id);
            $branches = Branch::get();
            $halls = Hall::get();
            return view('halls.edit', [
                'booking' => $booking,
                'branches' => $branches,
                'halls' => $halls,
            ]);
        } catch (Exception $exception) {
            return redirect()->back()->with('danger', $exception->getMessage())->withInput();
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        try {
            $booking = Booking::findOrFail($id);
            DB::beginTransaction();
            $data = $this->validate($request, [
                'booked_by' => 'required|string|max:191',
                'reason' => 'required|string|max:191',
                'date' => 'required|date',
                'start_time' => 'required|date_format:H:i',
                'end_time' => 'required|date_format:H:i',
                'branch_id' => 'required|numeric',
                'hall_id' => 'required|numeric',
            ]);
            $booking->update($data);
            DB::commit();
            session()->flash('success', 'booking has been updated successfully');
            return redirect()->back();
        } catch (Exception $exception) {
            DB::rollBack();
            return redirect()->back()->with('danger', $exception->getMessage())->withInput();
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        try {
            $booking = Booking::findOrFail($id);
            $booking->delete();
            session()->flash('danger', 'booking has been deleted');
            return redirect()->back();
        } catch (Exception $exception) {
            return redirect()->back()->with('danger', $exception->getMessage())->withInput();
        }
    }

    public function fetchHalls(Request $request)
    {
        $branch = $request->post('branch');
        $halls = Hall::where('branch_id', $branch)->get();
        return response()->json($halls);
    }

    public function isAvailable(Request $request)
    {
        $branch = $request->post('branch');
        $hall = $request->post('hall');
        $date = $request->post('date');
        $start_time = $request->post('start_time');
        $end_time = $request->post('end_time');
        $booking = Booking::where('branch_id', $branch)
            ->where('hall_id', $hall)
            ->whereDate('date', date('y-m-d',strtotime($date)))
            ->whereDate('start_time','>=',date('H:i',strtotime($start_time)))
            ->orWhereDate('start_time','<=',date('H:i',strtotime($end_time)))
            ->orWhereDate('end_time','>=',date('H:i',strtotime($start_time)))
            ->orWhereDate('end_time','<=',date('H:i',strtotime($end_time)))
            ->get();
            return response()->json($booking);
    }
}

resources/views/bookings/create.blade.php
@include('partials.header')
@include('partials.navbar')
<div class="container">
    <div class="card">
        <div class="card-header">
            <h3>Add bookings</h3>
            <a href="{{ route('bookings.index') }}" class="btn btn-success">All bookings</a>
        </div>
        <div class="availability">
              @include('_partial.notification')
        </div>
        <div class="card-body">
        <form action="{{route('bookings.store')}}" method="post">
          @csrf
          <div class="mb-3">
            <label for="branch_id">Branch *</label>
            <select name="branch_id" class="form-control lead" id="branch">
                <option disabled selected>Select branch</option>
                @forelse($branches as $branch)
                    <option value="{{ $branch->id }}"  class="form-control lead">{{ $branch->branch }}</option>
                @empty
                    <option disabled selected>No branch</option>
                @endforelse
            </select>
        </div>
        <div class="mb-3">
            <label for="hall_id">Hall *</label>
            <select name="hall_id" class="form-control lead" id="hall">
                
            </select>
        </div>
        <div class="mb-3">
            <label for="" class="form-label">booked_by</label>
            <input type="text" name="booked_by" class="form-control">
        </div>
        <div class="mb-3">
            <label for="" class="form-label">date</label>
            <input type="date" id="date" name="date" class="form-control">
        </div>
        <div class="mb-3">
            <label for="" class="form-label">start_time</label>
            <input type="time" id="start_time" name="start_time" class="form-control">
        </div>
        <div class="mb-3">
            <label for="" class="form-label">end_time</label>
            <input type="time" id="end_time" name="end_time" class="form-control">
        </div>
        <div class="mb-3">
            <label for="" class="form-label">Reason</label>
            <textarea name="reason" class="form-control"></textarea>
        </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>
</div>
<script type="text/javascript">
    $(document).ready(function(){
      $('#branch').change(function(){
          $('#hall').html('');
        var branch=$('#branch').val();
        var base=$('base').attr('href');
        var url="{{route('bookings.fetchhalls')}}";
        var data={
          branch:branch,
        }
        $.ajax({
           type:"POST",
           headers: {
      'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
    },
           data:data,
           url:url,
           success: handleData,
        });
        function handleData(res,resText,jqxhr){
         if(jqxhr.status==200)
         {
           console.log(res);
           $.each(res,function(index,element){
            var abc=` <option value="`+element.id+`" class="form-control lead">`+element.hall+`</option>`
            $('#hall').append(abc);
        });

         }
        }
      });
      $('#end_time').change(function(){
          var branch=$('#branch').val();
          var hall=$('#hall').val();
          var date=$('#date').val();
          var start_time=$('#start_time').val();
          var end_time=$('#end_time').val();
          var base=$('base').attr('href');
        var url="{{route('bookings.isavailable')}}";
        var data={
          branch:branch,
          hall:hall,
          date:date,
          start_time:start_time,
          end_time:end_time,
        }
        $.ajax({
           type:"POST",
           headers: {
      'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
    },
           data:data,
           url:url,
           success: handleResponse,
        });
        function handleResponse(res,resText,jqxhr){
         if(jqxhr.status==200)
         {
           console.log(res);
           if(res.length >0)
           {
               window.alert('not available');
           }
           else{
             window.alert('available');
           }

         }
        }
      });
    });
  </script>
@include('partials.footer')

resources/views/bookings/edit.blade.php
@include('partial.header')
@include('partial.navbar')
<div class="container">
    <div class="card">
            <div class="card-header">
                <h3>Update  subscribes</h3>
                <a href="{{route('subscribes.index')}}" class="btn btn-success">All subscribes</a>
            </div>
            <div>
              @include('_partial.notification')
            </div>
            <div class="card-body">
            <form action="{{route('subscribes.update',$subscribe->id)}}" method="post">
              @csrf
              @method('PUT')
                <div class="mb-3">
                    <label for="person_id">Person *</label>
                    <select name="person_id" class="form-control lead">
                        @forelse($persons as $person)
                            <option value="{{ $person->id }}" class="form-control lead">{{ $person->name }}</option>
                        @empty
                            <option disabled selected>No person</option>
                        @endforelse
                    </select>
                </div>
                <div class="mb-3">
                    <label for="package_id">Package *</label>
                    <select name="package_id" class="form-control lead">
                        @forelse($packages as $package)
                            <option value="{{ $package->id }}" class="form-control lead">{{ $package->name }}</option>
                        @empty
                            <option disabled selected>No package</option>
                        @endforelse
                    </select>
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
            </div>
    </div>
</div>
@include('partial.footer')

resources/views/bookings/index.blade.php
@include('partials.header')
@include('partials.navbar')
<div class="container">
    <div class="card">
        <div class="card-header">
            <h3>List of bookings</h3>
            <a href="{{ route('bookings.create') }}" class="btn btn-success">Add new</a>
        </div>
        <div>
              @include('_partial.notification')
            </div>
        <div class="card-body">
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Branch</th>
                        <th scope="col">Hall</th>
                        <th scope="col">Date</th>
                        <th scope="col">Start Time</th>
                        <th scope="col">End Time</th>
                        <th scope="col">Reason</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($bookings as $booking)
                    <tr>
                    <th scope="row">{{$loop->index+1}}</th>
                        <td>{{$booking->branch->branch}}</td>
                        <td>{{$booking->hall->hall}}</td>
                        <td>{{$booking->date}}</td>
                        <td>{{$booking->start_time}}</td>
                        <td>{{$booking->end_time}}</td>
                        <td>{{$booking->reason}}</td>
                        <td>
                            <div class="d-flex">
                                <form action="{{ route('bookings.destroy', $booking->id) }}" method="post">
                                    @csrf
                                    @method('delete')
                                    <button type="submit" class="btn btn-danger ">Delete</button>
                                </form>
                            </div>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>
@include('partials.footer')