routes/web.php
<?php

use App\Http\Controllers\Front\BookingController;
use App\Http\Controllers\Front\BranchController;
use App\Http\Controllers\Front\HallController;
use App\Http\Controllers\Front\LandingPageController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('index');
// });

Route::get('/',[LandingPageController::class,'index'])->name('landingpage');

// branch
Route::resource('branches',BranchController::class);
// hall
Route::resource('halls',HallController::class);
// booking
Route::resource('bookings',BookingController::class);

Route::post('/bookings/fetchhalls',[BookingController::class,'fetchHalls'])->name('bookings.fetchhalls');
Route::post('/bookings/isavailable',[BookingController::class,'isAvailable'])->name('bookings.isavailable');

app/Models/Hall.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Hall extends Model
{
    use HasFactory;

    protected $table="halls";
    protected $fillable=['hall','branch_id'];


    public function branch()
    {
        return $this->belongsTo('App\Models\Branch');
    }
    public function bookings()
    {
        return $this->hasMany('App\Models\Booking');
    }
}

app/Http/Controllers/Front/HallController.php
<?php

namespace App\Http\Controllers\Front;

use App\Http\Controllers\Controller;
use App\Models\Branch;
use App\Models\Hall;
use Exception;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class HallController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $halls=Hall::get();
        return view('halls.index',[
            'halls'=>$halls,
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $branches=Branch::get();
        return view('halls.create',[
            'branches'=>$branches,
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        try
        {
            DB::beginTransaction();
            $data=$this->validate($request,[
                'hall'=>'required|string|max:191',
                'branch_id'=>'required|numeric',
            ]);
             Hall::create($data);
             DB::commit();
            session()->flash('success','hall has been created successfully');
            return redirect()->back();
        }catch(Exception $exception){
            DB::rollBack();
            return redirect()->back()->with('danger', $exception->getMessage())->withInput();
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
       try
       {
        $hall=Hall::findOrFail($id);
        $branches=Branch::get();
        return view('halls.edit',[
            'hall'=>$hall,
            'branches'=>$branches,
        ]);
       }catch(Exception $exception){
        return redirect()->back()->with('danger', $exception->getMessage())->withInput();
    }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
       try
       {
        $hall=Hall::findOrFail($id);
        DB::beginTransaction();
        $data=$this->validate($request,[
            'hall'=>'required|string|max:191',
            'branch_id'=>'required|numeric',
        ]);
        $hall->update($data);
        DB::commit();
        session()->flash('success','hall has been updated successfully');
        return redirect()->back();
       }catch(Exception $exception){
        DB::rollBack();
        return redirect()->back()->with('danger', $exception->getMessage())->withInput();
    }
}

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
       try
       {
        $hall= Hall::findOrFail($id);
        $hall->delete();
        session()->flash('danger','hall has been deleted');
        return redirect()->back();
       }catch(Exception $exception){
        return redirect()->back()->with('danger', $exception->getMessage())->withInput();
    }
    }
}

resources/views/halls/create.blade.php
@include('partials.header')
@include('partials.navbar')
<div class="container">
    <div class="card">
        <div class="card-header">
            <h3>Add halls</h3>
            <a href="{{ route('halls.index') }}" class="btn btn-success">All halls</a>
        </div>
        <div>
            @include('_partial.notification')
        </div>
        <div class="card-body">
            <form action="{{ route('halls.store') }}" method="post">
                @csrf
                <div class="mb-3">
                    <label for="branch_id">Branch *</label>
                    <select name="branch_id" class="form-control lead">
                        @forelse($branches as $branch)
                            <option value="{{ $branch->id }}" class="form-control lead">{{ $branch->branch }}</option>
                        @empty
                            <option disabled selected>No branch</option>
                        @endforelse
                    </select>
                </div>
                <div class="mb-3">
                    <label for="" class="form-label">Hall</label>
                    <input type="text" name="hall" class="form-control">
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>
</div>
@include('partials.footer')

resources/views/halls/edit.blade.php
@include('partials.header')
@include('partials.navbar')
<div class="container">
    <div class="card">
            <div class="card-header">
                <h3>Update  halls</h3>
                <a href="{{route('halls.index')}}" class="btn btn-success">All halls</a>
            </div>
            <div>
              @include('_partial.notification')
            </div>
            <div class="card-body">
            <form action="{{route('halls.update',$hall->id)}}" method="post">
              @csrf
              @method('PUT')
              <div class="mb-3">
                <label for="branch_id">Branch *</label>
                <select name="branch_id" class="form-control lead">
                    @forelse($branches as $branch)
                        <option value="{{ $branch->id }}" class="form-control lead">{{ $branch->branch }}</option>
                    @empty
                        <option disabled selected>No branch</option>
                    @endforelse
                </select>
            </div>
            <div class="mb-3">
                <label for="" class="form-label">Hall</label>
                <input type="text" name="hall" class="form-control" value="{{$hall->hall}}">
            </div>
                    <button type="submit" class="btn btn-primary">Submit</button>
                  </form>
            </div>
    </div>
</div>
@include('partials.footer')

resources/views/halls/index.blade.php
@include('partials.header')
@include('partials.navbar')
<div class="container">
    <div class="card">
        <div class="card-header">
            <h3>List of halls</h3>
            <a href="{{ route('halls.create') }}" class="btn btn-success">Add new</a>
        </div>
        <div>
            @include('_partial.notification')
          </div>
        <div class="card-body">
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Branch</th>
                        <th scope="col">Hall</th>
                        <th scope="col">Action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($halls as $hall)
                    <tr>
                        <th scope="row">{{ $loop->index + 1 }}</th>
                        <td>{{ $hall->branch->branch }}</td>
                        <td>{{ $hall->hall }}</td>
                        <td>
                            <div class="d-flex">
                                <a href="{{route('halls.edit',$hall->id)}}" class="btn btn-info">Edit</a>
                            &nbsp;&nbsp;
                            <form action="{{route('halls.destroy',$hall->id)}}" method="post">
                              @csrf
                              @method('delete')
                              <button type="submit" class="btn btn-danger">Delete</button>
                            </form>
                            </div>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>
@include('partials.footer')