routes/web.php
<?php

use App\Http\Controllers\Front\BookingController;
use App\Http\Controllers\Front\BranchController;
use App\Http\Controllers\Front\HallController;
use App\Http\Controllers\Front\LandingPageController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('index');
// });

Route::get('/',[LandingPageController::class,'index'])->name('landingpage');

// branch
Route::resource('branches',BranchController::class);
// hall
Route::resource('halls',HallController::class);
// booking
Route::resource('bookings',BookingController::class);

Route::post('/bookings/fetchhalls',[BookingController::class,'fetchHalls'])->name('bookings.fetchhalls');
Route::post('/bookings/isavailable',[BookingController::class,'isAvailable'])->name('bookings.isavailable');

app/Models/Branch.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Branch extends Model
{
    use HasFactory;
    
    protected $table="branches";
    protected $fillable=['branch'];

    public function halls()
    {
        return $this->hasMany('App\Models\Hall');
    }

    public function bookings()
    {
        return $this->hasMany('App\Models\Booking');
    }
}

app/Http/Controllers/Front/BranchController.php
<?php

namespace App\Http\Controllers\Front;

use Exception;
use App\Models\Branch;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use App\Http\Controllers\Controller;

class BranchController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $branches=Branch::get();
        return view('branches.index',[
            'branches'=>$branches,
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('branches.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        try
        {
            DB::beginTransaction();
            $data=$this->validate($request,[
                'branch'=>'required|string|max:191',
            ]);
             Branch::create($data);
             DB::commit();
            session()->flash('success','branch has been created successfully');
            return redirect()->back();
        }catch(Exception $exception){
            DB::rollBack();
            return redirect()->back()->with('danger', $exception->getMessage())->withInput();
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
       try
       {
        $branch=Branch::findOrFail($id);
        return view('branches.edit',[
            'branch'=>$branch,
        ]);
       }catch(Exception $exception){
        return redirect()->back()->with('danger', $exception->getMessage())->withInput();
    }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
       try
       {
        $branch=Branch::findOrFail($id);
        DB::beginTransaction();
        $data=$this->validate($request,[
            'branch'=>'required|string|max:191',
        ]);
        $branch->update($data);
        DB::commit();
        session()->flash('success','branch has been updated successfully');
        return redirect()->back();
       }catch(Exception $exception){
        DB::rollBack();
        return redirect()->back()->with('danger', $exception->getMessage())->withInput();
    }
}

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
       try
       {
        $branch= Branch::findOrFail($id);
        $branch->delete();
        session()->flash('danger','branch has been deleted');
        return redirect()->back();
       }catch(Exception $exception){
        return redirect()->back()->with('danger', $exception->getMessage())->withInput();
    }
    }
}

resources/views/branches/create.blade.php
@include('partials.header')
@include('partials.navbar')
<div class="container">
    <div class="card">
            <div class="card-header">
                <h3>Add branches</h3>
            <a href="{{route('branches.index')}}" class="btn btn-success">All branches</a>
            </div>
            <div>
              @include('_partial.notification')
            </div>
            <div class="card-body">
            <form action="{{route('branches.store')}}" method="post">
              @csrf
                    <div class="mb-3">
                      <label for="" class="form-label">Branch</label>
                      <input type="text"  name="branch" class="form-control">
                    </div>
                    <button type="submit" class="btn btn-primary">Submit</button>
                  </form>
            </div>
    </div>
</div>
@include('partials.footer')

resources/views/branches/edit.blade.php
@include('partials.header')
@include('partials.navbar')
<div class="container">
    <div class="card">
            <div class="card-header">
                <h3>Update  Branch</h3>
                <a href="{{route('branches.index')}}" class="btn btn-success">All Branches</a>
            </div>
            <div>
              @include('_partial.notification')
            </div>
            <div class="card-body">
            <form action="{{route('branches.update',$branch->id)}}" method="post">
              @csrf
              @method('PUT')
                    <div class="mb-3">
                      <label for="" class="form-label">Branch</label>
                    <input type="text" name="branch" class="form-control" value="{{$branch->branch}}">
                    </div>
                    <button type="submit" class="btn btn-primary">Submit</button>
                  </form>
            </div>
    </div>
</div>
@include('partials.footer')

resources/views/branches/index.blade.php
@include('partials.header')
@include('partials.navbar')
<div class="container">
    <div class="card">
        <div class="card-header">
            <h3>List of Branches</h3>
            <a href="{{ route('branches.create') }}" class="btn btn-success">Add new</a>
        </div>
        <div>
            @include('_partial.notification')
        </div>
        <div class="card-body">
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Branch</th>
                        <th scope="col">Action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($branches as $branch)
                        <tr>
                            <th scope="row">{{ $loop->index + 1 }}</th>
                            <td>{{ $branch->branch }}</td>
                                    <td>
                                <div class="d-flex">
                                    <a href="{{ route('branches.edit', $branch->id) }}" class="btn btn-info">Edit</a>
                                    &nbsp;&nbsp;
                                    <form action="{{ route('branches.destroy', $branch->id) }}" method="post">
                                        @csrf
                                        @method('delete')
                                        <button type="submit" class="btn btn-danger ">Delete</button>
                                    </form>
                                </div>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>
@include('partials.footer')